<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CHECKOUT</name>
   <tag></tag>
   <elementGuidId>f44f55c7-59d8-4f38-9304-3401408e0822</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div[2]/div/div[2]/div/div[2]/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;CHECKOUT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce6853b6-57c8-4dfe-a6da-7761182de223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.evershop.io/checkout</value>
      <webElementGuid>3b1ae3c4-16e5-4d39-be24-6647667d865d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary</value>
      <webElementGuid>d963464d-05c1-43e9-80e3-269c972e5692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT</value>
      <webElementGuid>e7182bd9-8fe8-45f0-a380-a669f3a2fb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/main[@class=&quot;content&quot;]/div[2]/div[@class=&quot;cart page-width&quot;]/div[@class=&quot;cart-page-middle&quot;]/div[@class=&quot;grid gap-16 grid-cols-1 md:grid-cols-4&quot;]/div[@class=&quot;col-span-1 md:col-span-1&quot;]/div[@class=&quot;summary&quot;]/div[@class=&quot;shopping-cart-checkout-btn flex justify-between mt-8&quot;]/a[@class=&quot;button primary&quot;]</value>
      <webElementGuid>d4f22941-cbcd-458b-bf3c-f63c94547ca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div[2]/div/div[2]/div/div[2]/div/div[2]/a</value>
      <webElementGuid>a1950af9-f6c7-4dc7-acd5-a614a7f5b2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$874.00'])[4]/following::a[1]</value>
      <webElementGuid>23e5c216-d35e-4fd0-84f5-21b561cd4488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Inclusive of tax $0.00)'])[1]/following::a[1]</value>
      <webElementGuid>26311b4c-7abd-4adf-b00f-53bbf5e2d0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2022 Evershop. All Rights Reserved.'])[1]/preceding::a[1]</value>
      <webElementGuid>b0d0184d-d071-4a51-8791-84ab0e180ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.evershop.io/checkout')]</value>
      <webElementGuid>af3eb4df-2820-4217-926b-b6294243498e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/a</value>
      <webElementGuid>b35b4422-19b0-4bba-8227-c37981d9dcb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.evershop.io/checkout' and (text() = 'CHECKOUT' or . = 'CHECKOUT')]</value>
      <webElementGuid>ba98946f-7345-4d05-841c-e8e4bda3f786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$807.00'])[4]/following::a[1]</value>
      <webElementGuid>11d3bc21-f877-4a38-9a72-3eb61e111209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
