<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Shop MenWomenAbout us1</name>
   <tag></tag>
   <elementGuidId>5db7e879-b30a-455f-bbfb-5b9627125849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.header.grid.grid-cols-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Shop ❤️MenWomenAbout us1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0c126d8-b5de-42ee-819c-8e9d29f985c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header grid grid-cols-3</value>
      <webElementGuid>35df056e-ffb6-49b5-8d0e-da21f1f6a60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop ❤️MenWomenAbout us1</value>
      <webElementGuid>027c8bcb-e562-4976-89a7-81113838eccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;header grid grid-cols-3&quot;]</value>
      <webElementGuid>c53ed31e-34f5-4afb-9d9c-fdb9f7768461</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]</value>
      <webElementGuid>b35dbea8-8ab0-4aae-a655-1f7f1369d2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>5ca5c035-e625-445e-942a-d24f16c4feba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Shop ❤️MenWomenAbout us1' or . = 'Shop ❤️MenWomenAbout us1')]</value>
      <webElementGuid>a80ac497-6717-464e-89c0-49c27447bd4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
