<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postcode_addresspostcode</name>
   <tag></tag>
   <elementGuidId>4f352f3f-df42-44be-8740-46eb4a913b78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;address[postcode]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='address[postcode]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Postcode&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63c1828a-4a85-4297-87ec-b1baa9575e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5676f9fc-a3cc-4885-98dc-debe22b543c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[postcode]</value>
      <webElementGuid>fa21bcbc-b89a-4ed0-a200-792eb0dc1449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Postcode</value>
      <webElementGuid>187e1532-f237-46e5-97ca-af8e2ed15688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkoutShippingAddressForm&quot;)/div[1]/div[@class=&quot;grid grid-cols-2 gap-4 mt-4&quot;]/div[2]/div[@class=&quot;form-field-container null&quot;]/div[@class=&quot;field-wrapper flex flex-grow&quot;]/input[1]</value>
      <webElementGuid>e311a6a5-05c7-4f2f-a6b7-4ee877052f8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='address[postcode]']</value>
      <webElementGuid>f62af1d8-e1ba-4735-b86c-03e4b6c35975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutShippingAddressForm']/div/div[5]/div[2]/div/div/input</value>
      <webElementGuid>af490958-a359-40c6-980f-644fe29807a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>aca69752-52a3-450d-9339-9eba5f2b341a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address[postcode]' and @placeholder = 'Postcode']</value>
      <webElementGuid>ed33b35a-a70f-4734-bba4-b9d3cf9658e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
