<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pilih Provinsi</name>
   <tag></tag>
   <elementGuidId>cfb4f8e4-9744-400e-9f0b-f76eb50b9ec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='address[province]']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='address$[province]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Province&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>01c98c09-3da3-4213-b1ad-035661af864d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field</value>
      <webElementGuid>0809664b-fbbd-4204-aaa1-2cd2cec49dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address[province]</value>
      <webElementGuid>36239053-f52f-426e-9ef3-ab327b7e372c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[province]</value>
      <webElementGuid>016ff659-68b9-4c05-b108-ff23e1217eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Province</value>
      <webElementGuid>7dbf5680-e7d8-470d-a4a2-50a636ef18ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProvinceAnhuiBeijingChongqingFujianGansuGuangdongGuangxiGuizhouHainanHebeiHeilongjiangHenanHubeiHunanJiangsuJiangxiJilinLiaoningNei MongolNingxiaQinghaiShaanxiShandongShanghaiShanxiSichuanTianjinXinjiangXizangYunnanZhejiang</value>
      <webElementGuid>1a23a31c-a6b6-4c0a-8510-fa213a41c12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='address$[province]']</value>
      <webElementGuid>4134343b-0583-42cd-8d73-e7f5df68ac25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='address[province]']</value>
      <webElementGuid>221375b9-b131-4e42-be10-707488ab50c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutShippingAddressForm']/div/div[5]/div/div/div/select</value>
      <webElementGuid>936c30d8-d2a7-4ad2-a747-d0ca16a4edb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[1]/following::select[1]</value>
      <webElementGuid>5b65aa55-fc47-405d-8b3e-2cc1dc459d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>b244826e-f46a-4a58-a319-963514a242ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postcode'])[1]/preceding::select[1]</value>
      <webElementGuid>c00b0b7b-b8ea-4850-ba74-6781007ca6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Method'])[1]/preceding::select[1]</value>
      <webElementGuid>da1f3374-015c-42ca-8a2d-55bf19a2f470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/select</value>
      <webElementGuid>ca05fa65-54ea-4877-80d6-7777534e5cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'address[province]' and @name = 'address[province]' and @placeholder = 'Province' and (text() = 'ProvinceAnhuiBeijingChongqingFujianGansuGuangdongGuangxiGuizhouHainanHebeiHeilongjiangHenanHubeiHunanJiangsuJiangxiJilinLiaoningNei MongolNingxiaQinghaiShaanxiShandongShanghaiShanxiSichuanTianjinXinjiangXizangYunnanZhejiang' or . = 'ProvinceAnhuiBeijingChongqingFujianGansuGuangdongGuangxiGuizhouHainanHebeiHeilongjiangHenanHubeiHunanJiangsuJiangxiJilinLiaoningNei MongolNingxiaQinghaiShaanxiShandongShanghaiShanxiSichuanTianjinXinjiangXizangYunnanZhejiang')]</value>
      <webElementGuid>fc0f8e6e-7b6c-4860-a574-02a68cae62d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
