<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Warna</name>
   <tag></tag>
   <elementGuidId>d011c2ee-0da8-4253-ba45-b57992b4ab43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div[2]/div[2]/div/div[2]/div[2]/div[2]/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > ul.variant-option-list.flex.justify-start.gap-2.flex-wrap</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//ul[contains(@class,'variant-option-list')]//*[normalize-space(text())='${warna}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;BlueBlackPink&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>d92d7c62-2845-460a-858a-a61e7e660eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>variant-option-list flex justify-start gap-2 flex-wrap</value>
      <webElementGuid>55de7519-62a7-4fe3-a1a9-71fcda944874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BlueBlackPink</value>
      <webElementGuid>c961c032-f124-4550-95f9-112aea97a70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[contains(@class,'variant-option-list')]//*[normalize-space(text())='${warna}']</value>
      <webElementGuid>d4c7660f-dc44-45b8-982a-11a61034264d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div[2]/div[2]/div/div[2]/div[2]/div[2]/ul</value>
      <webElementGuid>278be131-2d05-44fb-801d-2476c2689c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue'])[1]/following::ul[2]</value>
      <webElementGuid>53e03880-c2b6-45e8-980b-be7a0fb355d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/following::ul[2]</value>
      <webElementGuid>f08e9050-9af1-4747-a35b-c3423b7d6532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD TO CART'])[1]/preceding::ul[1]</value>
      <webElementGuid>81c81d2f-67e9-4c1f-b1c3-d5b204183f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2022 Evershop. All Rights Reserved.'])[1]/preceding::ul[1]</value>
      <webElementGuid>2e864ad8-2910-4375-940e-52e75bc1d7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul</value>
      <webElementGuid>8fdedd5e-26d0-4d8b-bc0d-28eb40820654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'BlueBlackPink' or . = 'BlueBlackPink')]</value>
      <webElementGuid>e34eb569-58c0-46b1-99db-d2c70c15c8e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
