<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_M</name>
   <tag></tag>
   <elementGuidId>60ef55f8-74be-4e24-926e-1de0d2bf1008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.variant-option-list.flex.justify-start.gap-2.flex-wrap > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div[2]/div[2]/div/div[2]/div[2]/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;M&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>45bdf8fb-b66e-4158-bc15-37464425963f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9d9e1e47-5c2b-43f5-b9c5-d102f792349d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>39bf090c-8ced-42b2-8ed6-0ebe30a63a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;product-detail&quot;]/div[@class=&quot;product-page-middle page-width&quot;]/div[@class=&quot;grid grid-cols-1 gap-12 md:grid-cols-2&quot;]/div[2]/div[@class=&quot;variant variant-container grid grid-cols-1 gap-4 mt-8&quot;]/div[1]/ul[@class=&quot;variant-option-list flex justify-start gap-2 flex-wrap&quot;]/li[1]/a[1]</value>
      <webElementGuid>4605b0a7-5f6f-4791-8682-6be2efc92bad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div[2]/div[2]/div/div[2]/div[2]/div/ul/li/a</value>
      <webElementGuid>0beab000-51c4-465b-9a87-f869bf8af6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'M')])[2]</value>
      <webElementGuid>379d4434-2693-4bed-8a4c-8e54d7028531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brown'])[1]/following::a[1]</value>
      <webElementGuid>c9d7c4be-9bf2-47e5-8252-29b7a4f49241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/following::a[1]</value>
      <webElementGuid>e5d2ebd4-fbc0-4ede-b9bf-8acc5acb330f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD TO CART'])[1]/preceding::a[4]</value>
      <webElementGuid>256959f3-73d9-4f8a-aa78-306e314c8fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2022 Evershop. All Rights Reserved.'])[1]/preceding::a[4]</value>
      <webElementGuid>002c1bf1-0ab0-47c6-941f-f37264ff326a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='M']/parent::*</value>
      <webElementGuid>e555eab7-18d4-4795-a3b2-e0ceaffb4ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>7b26cf5c-7e17-43f2-bae6-b65caae1d2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li/a</value>
      <webElementGuid>32a50b2b-1db1-486b-b097-86dc644c50ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'M' or . = 'M')]</value>
      <webElementGuid>2f842804-6dc7-4195-80d6-f9a4aa3c5837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
